import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Providers from '@/components/Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title:{
    default:'Create Next App',
   template:'%s | NextJs14'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}  suppressHydrationWarning={true}>
        <div className='container'>
          <Providers>
      <Navbar />
        {children}
        <ToastContainer />
        <Footer/>
          </Providers>
        </div>
        </body>
    </html>
  )
}
